---
version: 2.1

orbs:
  docker: circleci/docker@0.5.13

references:
  all_branches_and_tags: &all_branches_and_tags
    filters:
      branches:
        only: /.*/
      tags:
        only: /.*/
  any_tag: &any_tag
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /.*/

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/hadolint:
          <<: *all_branches_and_tags
          dockerfiles: Dockerfile
      - docker/publish:
          <<: *any_tag
          image: messari/aws-cli-eks-kube
          tag: ${CIRCLE_TAG}
          requires:
            - docker/hadolint
