version: 2.1

orbs:
  docker: circleci/docker@0.5.13

references:
  semver_tag_only: &semver_tag_only
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^[0-9]*\.[0-9]*\.[0-9]*$/

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          <<: *semver_tag_only
          image: messari/aws-cli-eks-kube:${CIRCLE_TAG}
