---
version: 2.1

orbs:
  docker: circleci/docker@0.5.13

references:
  all_branches_and_tags: &all_branches_and_tags
    filters:
      branches:
        only: /.*/
      tags:
        only: /.*/
  semver_tag_only: &semver_tag_only
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^[0-9]*\.[0-9]*\.[0-9]*$/

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/hadolint:
          <<: *all_branches_and_tags
          dockerfiles: Dockerfile
      - docker/publish:
          <<: *semver_tag_only
          image: messari/aws-cli-eks-kube
          tag: ${CIRCLE_TAG}
          requires:
            - docker/hadolint
